import "src/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "@/lib/providers";
import StarBackground from "@/components/starBg";
import NavBar from "@/components/navBar";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Resume",
  description: "Generated by Nukrobzero",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.className} bg-black`}>
        {/* <StarBackground /> */}
        <Providers>
          <main className="max-w-screen-2xl mx-auto grid lg:grid-cols-8 min-h-screen text-neutral-100">
            <div className="z-50 col-span-2">
              <NavBar />
            </div>
            <div className="container mx-auto col-span-6">{children}</div>
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
